package io.github.gaomjun.motionorientation

/**
 * Created by qq on 13/4/2017.
 */
enum class DeviceOrientation {
    DEVICE_ORIENTATION_UNKNOWN,
    DEVICE_ORIENTATION_PORTRAIT,
    DEVICE_ORIENTATION_UPSIDEDOWN,
    DEVICE_ORIENTATION_LANDSCAPERIGHT,
    DEVICE_ORIENTATION_LANDSCAPELEFT,
    DEVICE_ORIENTATION_FACEUP,
    DEVICE_ORIENTATION_FACEDOWN
}